[[plugins]]
repo='Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
    let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'gtags.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/unite-outline'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neocomplete'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''
on_ft = ['json']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = ['exs', 'ex']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yaml', 'ansible']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['Dockerfile']

[[plugins]]
repo = 'lambdalisue/vim-gita'
on_cmd = ['Gita']

[[plugins]]
repo = 'lambdalisue/vim-gista'
on_cmd = ['Gista']
