# Locale Settings
# Ensure consistent encoding across all shell instances
export LANG=C.UTF-8
export LC_CTYPE=C.UTF-8

# -g: declare on global scope
# -r: Readonly
typeset -g _ZDOTDIR=${0:A:h}

## Directories
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_CACHE_HOME=${HOME}/.cache
export XDG_DATA_HOME=${HOME}/.local/share

## Path
# "-U" denies duplicate path
typeset -g -U path PATH
typeset -g -U fpath FPATH
# (N-/): options that check the existing and evaluate symboric link
# N: NULL_GLOB, -: evaluate symbolic link, /: only allow directory
path=(
       ${HOME}/bin(N-/)
       ${HOME}/.local/bin(N-/)
       ${HOME}/.cargo/bin(N-/)
       ${GOPATH:-${HOME}/go}/bin(N-/)
       ${XDG_DATA_HOME}/mise/shims(N-/)
       /opt/homebrew/bin(N-/)

       $path
     )

