umask 022

## Mise
eval "$(mise activate zsh)"

## Sheldon
if (( $+commands[sheldon] )); then
  local sheldon_cache="$XDG_CACHE_HOME/sheldon/source.zsh"
  local sheldon_config="$XDG_CONFIG_HOME/sheldon/plugins.toml"
  if [[ ! -f "$sheldon_cache" || "$sheldon_config" -nt "$sheldon_cache" ]]; then
    mkdir -p "$(dirname "$sheldon_cache")"
    sheldon source > "$sheldon_cache"
  fi
  source "$sheldon_cache"
  rehash
fi
